// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6bN2oJ33ERI-wYV_L24shH4UAY9JSHc',
    appId: '1:40943690754:web:4a934daeaba57f3591731b',
    messagingSenderId: '40943690754',
    projectId: 'prototico-twoo',
    authDomain: 'prototico-twoo.firebaseapp.com',
    storageBucket: 'prototico-twoo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAww_Pal5OonnZ1XY6tH6K24ay_OLp0im8',
    appId: '1:40943690754:android:5e1ede32078c0ebe91731b',
    messagingSenderId: '40943690754',
    projectId: 'prototico-twoo',
    storageBucket: 'prototico-twoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVm0rSvkp3ndzxx5rIatGxOW_5V0Qo1M',
    appId: '1:40943690754:ios:908010531fed970d91731b',
    messagingSenderId: '40943690754',
    projectId: 'prototico-twoo',
    storageBucket: 'prototico-twoo.firebasestorage.app',
    iosBundleId: 'com.example.prototicoTwoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVm0rSvkp3ndzxx5rIatGxOW_5V0Qo1M',
    appId: '1:40943690754:ios:908010531fed970d91731b',
    messagingSenderId: '40943690754',
    projectId: 'prototico-twoo',
    storageBucket: 'prototico-twoo.firebasestorage.app',
    iosBundleId: 'com.example.prototicoTwoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_6bN2oJ33ERI-wYV_L24shH4UAY9JSHc',
    appId: '1:40943690754:web:c2b97cf73298aedc91731b',
    messagingSenderId: '40943690754',
    projectId: 'prototico-twoo',
    authDomain: 'prototico-twoo.firebaseapp.com',
    storageBucket: 'prototico-twoo.firebasestorage.app',
  );

}